# Generated by Django 2.0.13 on 2019-06-04 12:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='defautl text', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
