# Generated by Django 2.0.13 on 2019-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190604_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='empty comment', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('id', 'slug')},
        ),
    ]
