# Generated by Django 2.0.13 on 2019-06-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190605_1243'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together={('id', 'slug')},
        ),
    ]
