# Generated by Django 2.0.13 on 2019-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190605_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('posts', models.ManyToManyField(to='blog.Post')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
