# Generated by Django 2.0.13 on 2019-06-08 15:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_posttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTest',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='text'),
        ),
    ]
